name: Demo Bug
description: File a bug in the official demo
labels:
  - bug
  - demo
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I'm using the official demo at https://yume-chan.github.io/ya-webadb
          required: true
  - type: input
    attributes:
      label: Runtime
      description: Operating system, runtime name and version
      placeholder: e.g. macOS 12.1, Chrome 99
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      description: Device model and Android version
      placeholder: e.g. Pixel 5, Android 12
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
