name: Publish Package to npm
on:
  push:
    tags:
      - "v**"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js build --verbose
      - run: node common/scripts/install-run-rush.js publish -p --include-all --set-access-level public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
